DROP TABLE IF EXISTS `works`;
CREATE TABLE `works` (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  work_name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  status TINYINT(1) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
LOCK TABLES `works` WRITE;
